
[package]
name = "kmeans"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.2"
rayon = "1.8"
plotters = "0.3"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "experiments"
path = "src/scaling_experiments.rs"
